export const ActivityType = {
  WALKING: 'WALKING',
  CYCLING: 'CYCLING',
  PUBLIC_TRANSPORT: 'PUBLIC_TRANSPORT',
  RECYCLING: 'RECYCLING',
  ENERGY_SAVING: 'ENERGY_SAVING',
};

export const MeasurementUnit = {
  STEPS: 'STEPS',
  KILOMETERS: 'KILOMETERS',
  KWH: 'KWH',
  KILOGRAMS: 'KILOGRAMS',
};

export const VerificationStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
}; 